DROP DATABASE IF EXISTS CollegeDB;
CREATE DATABASE CollegeDB;
USE CollegeDB;

CREATE TABLE Cource(courceID INT(10) PRIMARY KEY ,courceName VARCHAR(20),Credits INT(10),departmentID INT(5));
INSERT INTO Cource VALUES (101,"BCA",4,201),(102,"BSC IT",5,204),(103,"BBA",4,210);
DESC Cource;
SELECT * FROM Cource;